#!/bin/bash

set -euo pipefail

function run_or_dry_run() {
  if [ -n "${DRY_RUN:-}" ]
  then
      echo "DRY_RUN: ${@}" >&2
  else
      "${@}"
  fi
}

source "$(dirname "${BASH_SOURCE[0]}")/env"

echo "build Gitit ${GITIT_BRANCH} (from '${HASKELL_IMAGE}') as '${IMAGE_NAME}'" >&2

run_or_dry_run docker build \
--build-arg=GITIT_BRANCH="${GITIT_BRANCH}" \
--build-arg=HASKELL_IMAGE="${HASKELL_IMAGE}" \
-f "${DOCKERFILE_PATH}" \
-t "${IMAGE_NAME}" \
.
