#!/bin/bash

set -euo pipefail

function run_or_dry_run() {
  if [ -n "${DRY_RUN:-}" ]
  then
      echo "DRY_RUN: ${@}" >&2
  else
      "${@}"
  fi
}

echo "${0}: processing..." >&2

if [ "${CACHE_TAG}" == master ]
then
    echo "push '${CACHE_TAG}' as 'latest'" >&2
    run_or_dry_run docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:latest"
    run_or_dry_run docker push "${DOCKER_REPO}:latest"
fi

echo "${0}: done" >&2
